<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.celements</groupId>
    <artifactId>celements-parent</artifactId>
    <version>7.1</version>
  </parent>
  <artifactId>celements-xwiki-velocity</artifactId>
  <version>7.2-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-commons</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-component</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-reference</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-config-source-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-config-source</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-servlet</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-xml</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- Commons -->
    <dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-beanutils</groupId>
      <artifactId>commons-beanutils</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-collections</groupId>
      <artifactId>commons-collections</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-configuration</groupId>
      <artifactId>commons-configuration</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-dbcp</groupId>
      <artifactId>commons-dbcp</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-fileupload</groupId>
      <artifactId>commons-fileupload</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-net</groupId>
      <artifactId>commons-net</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <!-- XWiki -->
    <dependency>
      <groupId>org.xwiki.platform</groupId>
      <artifactId>xwiki-core-properties</artifactId>
    </dependency>
    <dependency>
      <groupId>org.xwiki.platform</groupId>
      <artifactId>xwiki-core-script</artifactId>
    </dependency>
    <dependency>
      <groupId>org.xwiki.platform</groupId>
      <artifactId>xwiki-core-bridge</artifactId>
    </dependency>
    <dependency>
      <groupId>org.xwiki.platform</groupId>
      <artifactId>xwiki-core-management</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.velocity</groupId>
      <artifactId>velocity</artifactId>
    </dependency>
    <dependency>
      <groupId>velocity-tools</groupId>
      <artifactId>velocity-tools</artifactId>
      <version>1.4</version>
    </dependency>

    <!-- Spring -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- testing -->
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-base-tests</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>
  <scm>
    <connection>scm:git:git@github.com:celements/celements-base.git</connection>
    <developerConnection>scm:git:git@github.com:celements/celements-base.git</developerConnection>
    <url>https://github.com/celements/celements-base/celements-xwiki-velocity</url>
    <tag>HEAD</tag>
  </scm>
</project>
