<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>com.celements</groupId>
    <artifactId>celements-parent</artifactId>
    <version>7.1-RC1</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>celements-keycloak</artifactId>
  <version>7.1-SNAPSHOT</version>
  <description>Celements KeyCloak adapter</description>
  <dependencies>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-commons</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-component</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-config-source-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-config-source</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-reference</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-servlet</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-observation</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-model</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-spring-security</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.inject</groupId>
      <artifactId>javax.inject</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-oauth2-resource-server</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-oauth2-jose</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <scm>
    <connection>scm:git:git@github.com:celements/celements-base.git</connection>
    <developerConnection>scm:git:git@github.com:celements/celements-base.git</developerConnection>
    <url>https://github.com/celements/celements-base/celements-keycloak</url>
    <tag>HEAD</tag>
  </scm>
</project>
