<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.celements</groupId>
    <artifactId>celements-parent</artifactId>
    <version>7.1-SNAPSHOT</version>
  </parent>
  <artifactId>celements-xwiki-rendering-api</artifactId>
  <version>7.1-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-commons</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-component</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-reference</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-config-source-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-config-source</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-observation</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-velocity</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-xml</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-servlet</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>struts</groupId>
      <artifactId>struts</artifactId>
    </dependency>

    <!-- Spring -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- Commons -->
    <dependency>
      <groupId>commons-configuration</groupId>
      <artifactId>commons-configuration</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- XWiki -->
    <dependency>
      <groupId>org.xwiki.platform</groupId>
      <artifactId>xwiki-core-properties</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.xwiki.platform</groupId>
      <artifactId>xwiki-core-bridge</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.dom4j</groupId>
      <artifactId>dom4j</artifactId>
    </dependency>

    <!-- We need the Xerces dependency at runtime since we have an optimization for the Xerces
     parser (to tell it to cache DTD grammars). If it's not there then there's no DTD caching. -->
    <dependency>
      <groupId>xerces</groupId>
      <artifactId>xercesImpl</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- testing -->
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-base-tests</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <scm>
    <connection>scm:git:git@github.com:celements/celements-base.git</connection>
    <developerConnection>scm:git:git@github.com:celements/celements-base.git</developerConnection>
    <url>https://github.com/celements/celements-base/celements-xwiki-rendering-api</url>
    <tag>HEAD</tag>
  </scm>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <id>test-jar</id>
            <goals>
              <goal>test-jar</goal>
            </goals>
            <configuration>
              <includes>
                <include>**/scaffolding/**.class</include>
              </includes>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <configuration>
          <excludes>
            org/xwiki/rendering/syntax/Syntax.java,
            org/xwiki/rendering/syntax/SyntaxType.java,
            org/xwiki/rendering/renderer/printer/XHTMLWikiPrinter.java,
            org/xwiki/rendering/renderer/printer/XMLWikiPrinter.java,
            org/xwiki/rendering/renderer/printer/VoidWikiPrinter.java,
            org/xwiki/rendering/renderer/printer/LookaheadWikiPrinter.java,
            org/xwiki/rendering/renderer/printer/WrappingWikiPrinter.java,
            org/xwiki/rendering/listener/chaining/LookaheadChainingListener.java,
            org/xwiki/rendering/listener/chaining/TextOnNewLineStateChainingListener.java,
            org/xwiki/rendering/listener/chaining/EventType.java,
            org/xwiki/rendering/listener/chaining/EmptyBlockChainingListener.java,
            org/xwiki/rendering/listener/chaining/BlockStateChainingListener.java,
            org/xwiki/rendering/listener/chaining/GroupStateChainingListener.java,
            org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxMacroRenderer.java,
            org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxChainingRenderer.java,
            org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxEscapeHandler.java,
            org/xwiki/rendering/internal/renderer/xwiki20/XWikiSyntaxImageRenderer.java,
            org/xwiki/rendering/internal/renderer/xwiki20/reference/XWikiSyntaxResourceRenderer.java,
            org/xwiki/rendering/internal/renderer/plain/PlainTextRenderer.java,
            org/xwiki/rendering/internal/renderer/plain/PlainTextChainingRenderer.java,
            org/xwiki/rendering/internal/renderer/printer/XHTMLWriter.java,
            org/xwiki/rendering/internal/renderer/printer/XWikiSyntaxEscapeWikiPrinter.java,
            org/xwiki/rendering/internal/renderer/printer/WikiWriter.java,
            org/xwiki/rendering/internal/renderer/xhtml/AnnotatedXHTMLChainingRenderer.java,
            org/xwiki/rendering/internal/renderer/xhtml/link/DefaultXHTMLLinkRenderer.java,
            org/xwiki/rendering/internal/renderer/xhtml/AnnotatedXHTMLBlockRenderer.java,
            org/xwiki/rendering/internal/renderer/xhtml/XHTMLChainingRenderer.java,
            org/xwiki/rendering/internal/renderer/xhtml/XHTMLMacroRenderer.java,
            org/xwiki/rendering/internal/renderer/xhtml/XHTMLBlockRenderer.java,
            org/xwiki/rendering/internal/renderer/xhtml/image/DefaultXHTMLImageRenderer.java,
            org/xwiki/rendering/internal/renderer/xhtml/image/AnnotatedXHTMLImageRenderer.java,
            org/xwiki/rendering/internal/renderer/event/EventsChainingRenderer.java,
            org/xwiki/rendering/internal/renderer/event/EventRendererFactory.java,
            org/xwiki/rendering/internal/renderer/event/EventBlockRenderer.java,
            org/xwiki/rendering/internal/parser/XDOMGeneratorListener.java
          </excludes>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
